"""
ClimaFuse — Core configuration, constants, logging, and exceptions.
"""

from .config import Settings, settings
from .constants import (
    AIFS_FORECAST_STEPS,
    AIFS_OPERATIONAL_START_DATE,
    BMA_TEST_END_DATE,
    BMA_TEST_START_DATE,
    BMA_TRAIN_END_DATE,
    BMA_TRAIN_START_DATE,
    GFS_FORECAST_STEPS,
    IMD_MISSING_VALUE,
    IMD_RAIN_WINDOW_END_UTC,
    IMD_RAIN_WINDOW_START_UTC,
    IMD_RESOLUTIONS,
    LEAD_BUCKETS,
    LOCATION_IDS,
    LOCATION_REGIONS,
    MIN_SAMPLES,
    MODEL_IDS,
    OPERATIONAL_LOCATIONS,
    PRECIP_THRESHOLDS_MM,
    SEASONS,
    SOURCE_MODELS,
    VARIABLE_BOUNDS,
    VARIABLE_UNITS,
    VARIABLES,
    get_lead_bucket,
    get_season,
)
from .exceptions import (
    BMAPredictionError,
    BMATrainingError,
    ClimaFuseException,
    ConfigurationError,
    DataAlignmentError,
    DataRetrievalError,
    DegradedForecastError,
    LocationNotFoundError,
    ModelSourceError,
)
from .logging import get_logger, setup_logging

__all__ = [
    "settings",
    "Settings",
    "setup_logging",
    "get_logger",
    "OPERATIONAL_LOCATIONS",
    "LOCATION_IDS",
    "LOCATION_REGIONS",
    "SOURCE_MODELS",
    "MODEL_IDS",
    "VARIABLES",
    "VARIABLE_UNITS",
    "VARIABLE_BOUNDS",
    "IMD_RESOLUTIONS",
    "IMD_MISSING_VALUE",
    "IMD_RAIN_WINDOW_START_UTC",
    "IMD_RAIN_WINDOW_END_UTC",
    "BMA_TRAIN_START_DATE",
    "BMA_TRAIN_END_DATE",
    "BMA_TEST_START_DATE",
    "BMA_TEST_END_DATE",
    "AIFS_OPERATIONAL_START_DATE",
    "SEASONS",
    "get_season",
    "LEAD_BUCKETS",
    "get_lead_bucket",
    "MIN_SAMPLES",
    "PRECIP_THRESHOLDS_MM",
    "AIFS_FORECAST_STEPS",
    "GFS_FORECAST_STEPS",
    "ClimaFuseException",
    "ConfigurationError",
    "LocationNotFoundError",
    "ModelSourceError",
    "DataRetrievalError",
    "DataAlignmentError",
    "BMATrainingError",
    "BMAPredictionError",
    "DegradedForecastError",
]
